version: '3.8'
#           docker rm -f $(docker ps -aq) && docker rmi -f $(docker images -q)

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5672"  
      - "15673:15672" 
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hackathon_net
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5433}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d hackathon_db -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hackathon_net
  
  hr_manager:
    build:
      context: .
      dockerfile: hr_manager/Dockerfile
    ports:
      - "${HR_MANAGER_PORT:-5011}:8080"
    restart: always
    deploy:
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
      hr_director:
        condition: service_started
    networks:
      - hackathon_net

  hr_director:
    build:
      context: .
      dockerfile: hr_director/Dockerfile
    ports:
      - "${HR_DIRECTOR_PORT:-5012}:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__HackathonDbContext="Host=db;Port=5432;Database=hackathon_db;Username=postgres;Password=postgres;Include Error Detail=true"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    deploy:
      replicas: 1
    networks:
      - hackathon_net

  x-employee-base: &employee-base
    build:
      context: .
      dockerfile: employee/Dockerfile
    volumes:
      - ./shared-data-dir:/app/shared-data
    deploy:
      replicas: 1
    depends_on:
      rabbitmq:
        condition: service_healthy
      hr_manager:
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq  
      - RABBITMQ_QUEUE=preferences_queue
    networks:
      - hackathon_net

  teamlead-1:
    <<: *employee-base
    ports:
      - "${TEAMLEAD_1_PORT:-5001}:8080"
    environment:
      - EmployeeSettings__EmployeeType=teamlead
      - EmployeeSettings__EmployeeId=1

  teamlead-2:
    <<: *employee-base
    ports:
      - "${TEAMLEAD_2_PORT:-5002}:8080"
    environment:
      - EmployeeSettings__EmployeeType=teamlead
      - EmployeeSettings__EmployeeId=2

  teamlead-3:
    <<: *employee-base
    ports:
      - "${TEAMLEAD_3_PORT:-5003}:8080"
    environment:
      - EmployeeSettings__EmployeeType=teamlead
      - EmployeeSettings__EmployeeId=3

  teamlead-4:
    <<: *employee-base
    ports:
      - "${TEAMLEAD_4_PORT:-5004}:8080"
    environment:
      - EmployeeSettings__EmployeeType=teamlead
      - EmployeeSettings__EmployeeId=4

  teamlead-5:
    <<: *employee-base
    ports:
      - "${TEAMLEAD_5_PORT:-5005}:8080"
    environment:
      - EmployeeSettings__EmployeeType=teamlead
      - EmployeeSettings__EmployeeId=5

  junior-1:
    <<: *employee-base
    ports:
      - "${JUNIOR_1_PORT:-6001}:8080"
    environment:
      - EmployeeSettings__EmployeeType=junior
      - EmployeeSettings__EmployeeId=1

  junior-2:
    <<: *employee-base
    ports:
      - "${JUNIOR_2_PORT:-6002}:8080"
    environment:
      - EmployeeSettings__EmployeeType=junior
      - EmployeeSettings__EmployeeId=2

  junior-3:
    <<: *employee-base
    ports:
      - "${JUNIOR_3_PORT:-6003}:8080"
    environment:
      - EmployeeSettings__EmployeeType=junior
      - EmployeeSettings__EmployeeId=3

  junior-4:
    <<: *employee-base
    ports:
      - "${JUNIOR_4_PORT:-6004}:8080"
    environment:
      - EmployeeSettings__EmployeeType=junior
      - EmployeeSettings__EmployeeId=4

  junior-5:
    <<: *employee-base
    ports:
      - "${JUNIOR_5_PORT:-6005}:8080"
    environment:
      - EmployeeSettings__EmployeeType=junior
      - EmployeeSettings__EmployeeId=5

networks:
  hackathon_net:
    driver: bridge
